<?php
if (!isset($_GET["id"])) {
    header("LOCATION: ./"); exit;
}
$alert = ConfigManager::getAlertById($_GET["id"]);
if (!$alert->id) {
    header("LOCATION: ./"); exit;
}
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    if (isset($_POST["id"]) && $_POST["id"] == $_GET["id"]) {
        ConfigManager::deleteAlert($alert);
    }
    header("LOCATION: ./"); exit;
}
?>
<form action="" method="post">
    <fieldset>
        <legend>Supprimer cette alerte ?</legend>
        <ul>
            <li>Titre : <?php echo htmlspecialchars($alert->title); ?></li>
            <li>Url : <?php echo htmlspecialchars($alert->url); ?></li>
        </ul>
        <p>
            <input type="hidden" name="id" value="<?php echo $_GET["id"]; ?>" />
            <input type="submit" value="Oui" style="font-weight: bold;" />
            <a href="./">Non</a>
        </p>
    </fieldset>
</form>
