<?php $alerts = ConfigManager::getAlerts(); ?>
<a href="?a=form">Ajouter une alerte</a>
<table style="width: 100%;">
    <thead>
        <tr>
            <th>E-Mail</th>
            <th>Titre</th>
            <th>URL</th>
            <th>Intervalle</th>
            <th>Prix</th>
            <th>Villes</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
    <?php if (0 == count($alerts)) : ?>
        <tr>
            <td colspan="4">Aucune alertes créées.</td>
        </tr>
    <?php else: ?>
        <?php foreach ($alerts AS $alert) : ?>
        <tr>
            <td><?php echo htmlspecialchars($alert->email); ?></td>
            <td><?php echo htmlspecialchars($alert->title); ?></td>
            <td>
                <a href="<?php echo htmlspecialchars($alert->url); ?>"><?php
                    echo str_replace("http://www.leboncoin.fr", "", htmlspecialchars($alert->url)); ?></a>
            </td>
            <td><?php echo (int)$alert->interval; ?> mins</td>
            <td>
                <?php if ($alert->price_min != -1 && $alert->price_max != -1) : ?>
                entre <?php echo $alert->price_min; ?>€ et <?php echo $alert->price_max; ?>€
                <?php elseif ($alert->price_min != -1) : ?>
                à partir de <?php echo $alert->price_min; ?>€
                <?php elseif ($alert->price_max != -1) : ?>
                jusque <?php echo $alert->price_max; ?>€
                <?php else: ?>
                -
                <?php endif; ?>
            </td>
            <td>
                <?php if ($alert->cities) : ?>
                <ul style="margin: 0; padding: 0 0 0 15px;"><li>
                <?php echo str_replace("\n", "</li><li>", htmlspecialchars($alert->cities)); ?>
                </li></ul>
                <?php else: ?>
                -
                <?php endif; ?>
            </td>
            <td>
                <a href="?a=form&amp;id=<?php echo $alert->id; ?>">modifier</a> |
                <a href="?a=form-delete&amp;id=<?php echo $alert->id; ?>">supprimer</a>
            </td>
        </tr>
        <?php endforeach; ?>
    <?php endif; ?>
    </tbody>
</table>
